// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlqiOvoM57U7fV0JHIkOsNmgTDtZLL_-I',
    appId: '1:93425537201:web:9b0e338b70fa64603a1290',
    messagingSenderId: '93425537201',
    projectId: 'clickbill-e7229',
    authDomain: 'clickbill-e7229.firebaseapp.com',
    storageBucket: 'clickbill-e7229.appspot.com',
    measurementId: 'G-TXXPWM1FMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5ZjzT41yN6lemQ1JO_shR7liGikjwSrk',
    appId: '1:93425537201:android:cde4e78b10b219473a1290',
    messagingSenderId: '93425537201',
    projectId: 'clickbill-e7229',
    storageBucket: 'clickbill-e7229.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGZzeWB0CnmUajd5HOI1sAhG_uiD3OS5o',
    appId: '1:93425537201:ios:fabb59e4ed4e73403a1290',
    messagingSenderId: '93425537201',
    projectId: 'clickbill-e7229',
    storageBucket: 'clickbill-e7229.appspot.com',
    iosBundleId: 'com.example.clickBill',
  );
}
